### PR TITLE
fix: add tsFormatter to moderate excludes

### LINKED ISSUE #688: ts-formatter should be removed from util/mod.ts
ts-formatter should be removed from `util/mod.ts` and added to the `exclude` moderate otherwise, when the code is bundled with `esbuild`, it cannot be used in the browser.

### PR DESCRIPTION
**Pull request by ryanleecode**
Resolves #688

### CODE REVIEW

**Review by harrysolovay — APPROVED** [review]

File: util/mod.ts [hunk 1]
```diff
@@ -1,10 +1,9 @@
-// moderate --exclude cache port.ts
+// moderate --exclude cache port.ts tsFormatter.ts"
```
Comment (tjjfvi) [inline util/mod.ts:1]: This trailing quote isn't right.

Comment (harrysolovay) [reply util/mod.ts:1]: Whoops... @ryanleecode will you please remove the quote along with #687 ?

Comment (tjjfvi) [reply util/mod.ts:1]: #690
