### PR TITLE
fix: misc. smoldot cleanup

### LINKED ISSUE #865: smoldot RPC connection exit issue
Run `examples/smoldot.eg.ts`.

### PR DESCRIPTION
**Pull request by harrysolovay**
Fixes #865
Closes #871

- enable one to override a codegened `ChainRune` with a smoldot connection using the `with` method
- reference counting chain count for graceful smoldot exit
- use `hex.encodePrefixed` instead of `hex.encode` (otherwise, smoldot storage retrievals throw)

### CODE REVIEW

File: rpc/smoldot.ts [hunk 1]
```diff
@@ -8,23 +8,29 @@ import { RpcEgressMessage } from "./rpc_messages.ts"
...
 export class SmoldotConnection extends Connection {
   // private so that the types don't need to be referenced when packaged
   private smoldotChainPending
   listening
   stopListening
+  chainsCount
 
   constructor(readonly props: SmoldotRpcConnProps) {
     super()
+    this.chainsCount = props.parachainSpec ? 2 : 1
```
Comment (tjjfvi) [inline rpc/smoldot.ts:26]: If this is only ever used to increment/decrement `count`, I believe it can always just be 1.

File: fluent/ChainRune.ts [hunk 2]
```diff
@@ -63,6 +63,11 @@ export class ChainRune<out C extends Chain, out U> extends Rune<C, U> {
     return Rune.rec({ connection, metadata }).into(this)
   }
 
+  with(connect: (signal: AbortSignal) => Connection) {
+    const connection = ConnectionRune.from(connect)
+    return Rune.rec({ connection, metadata: this.metadata }).into(ChainRune)
```
Comment (tjjfvi) [inline fluent/ChainRune.ts:68]: To preserve the chain name, I believe you'll need
```suggestion
    return Rune.rec({ connection, metadata: this.metadata } as C).into(ChainRune)
```

**Review by kratico — APPROVED** [review]
LGTM 🚀

**Review by tjjfvi — APPROVED** [review]
