### PR TITLE
fix: return empty list when no entries

### LINKED ISSUE #1169: Querying a double map with a partial key results in an exception
## Bug Report

Querying a double map with a partial key throws if there are no results on `v0.1.0-gamma.1`.

### Current Behavior

Throws exception due to `changeset` being undefined.

```
[...]/node_modules/capi/esm/fluent/StorageRune.js:39
            .map(([changeset, $key, $value]) => changeset.changes.map(([k, v]) => [

TypeError: Cannot read properties of undefined (reading 'changes')
    at RunMap.fn (file:///Users/raphael/Code/Kilt/capi%20example/node_modules/capi/esm/fluent/StorageRune.js:39:59)
    at RunMap._evaluate (file:///Users/raphael/Code/Kilt/capi%20example/node_modules/capi/esm/rune/ValueRune.js:117:44)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    from execution of the ValueRune instantiated
        at new Rune (file:///Users/raphael/Code/Kilt/capi%20example/node_modules/capi/esm/rune/Rune.js:44:23)
        at new ValueRune (file:///Users/raphael/Code/Kilt/capi%20example/node_modules/capi/esm/rune/ValueRune.js:4:8)
        at Function.new (file:///Users/raphael/Code/Kilt/capi%20example/node_modules/capi/esm/rune/ValueRune.js:6:16)
        at ValueRune.map (file:///Users/raphael/Code/Kilt/capi%20example/node_modules/capi/esm/rune/ValueRune.js:9:29)
        at StorageRune.entries (file:///Users/raphael/Code/Kilt/capi%20example/node_modules/capi/esm/fluent/StorageRune.js:39:14)
        at file:///Users/raphael/Code/Kilt/capi%20example/reproduce.js:10:50
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Expected Behavior

Returns empty array.

### Steps To Reproduce

`nets.js`
```js
import { net } from "capi/nets";

export const spiritnet = net.ws({ url: "wss://spiritnet.kilt.io" });
```
`reproduce.js`
```js
import { spiritnet } from "@capi/spiritnet";
import { ss58 } from "capi";

// works
console.log(await spiritnet.Did.ServiceEndpoints.entries({
    partialKey: [ss58.decode('4sJm5Zsvdi32hU88xbL3v6VQ877P4HLaWVYUXgcSyQR8URTu')[1]],
}).run())

// breaks
console.log(await spiritnet.Did.ServiceEndpoints.entries({
    partialKey: [ss58.decode('4saFtHZuY9UH1U7zasKLSkKsPogJjPqM1vT2k3ZJmrYmmr3g')[1]],
}).run())
```

### Environment

- Node: `v20.4.0`
- OS: macOS 13.4 (22F66)

### PR DESCRIPTION
**Pull request by harrysolovay**
Resolves #1169

### CODE REVIEW

File: fluent/StorageRune.ts [hunk 1]
```diff
@@ -84,12 +84,15 @@ export class StorageRune<
...
-        changeset!.changes.map(([k, v]) => [
-          $key.decode(hex.decode(k)),
-          v ? $value.decode(hex.decode(v)) : undefined,
-        ])
+        changeset
+          ? changeset.changes.map(([k, v]) => [
+            $key.decode(hex.decode(k)),
+            v ? $value.decode(hex.decode(v)) : undefined,
+          ])
+          : []
```
Comment (tjjfvi) [inline fluent/StorageRune.ts:92]: `changeset?.changes... ?? []`
