### PR TITLE
fix: add sort to otherSignatories

### LINKED ISSUE #992: multisigrune ratify SignatoriesOutOfOrder
```ts
Unhandled {
  value: ExtrinsicError: SignatoriesOutOfOrder
      at RunMap.fn (file:///home/ryan/Documents/Repositories/capi-multisig-app/node_modules/.pnpm/capi@0.1.0-beta.37/node_modules/capi/esm/fluent/ExtrinsicsEventsRune.js:31:28)
      at RunMap._evaluate (file:///home/ryan/Documents/Repositories/capi-multisig-app/node_modules/.pnpm/capi@0.1.0-beta.37/node_modules/capi/esm/rune/ValueRune.js:94:44)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async RunMap.evaluate (file:///home/ryan/Documents/Repositories/capi-multisig-app/node_modules/.pnpm/capi@0.1.0-beta.37/node_modules/capi/esm/rune/Rune.js:222:20)
      at async RunUnhandle._evaluate (file:///home/ryan/Documents/Repositories/capi-multisig-app/node_modules/.pnpm/capi@0.1.0-beta.37/node_modules/capi/esm/rune/ValueRune.js:149:24)
      at async RunUnhandle.evaluate (file:///home/ryan/Documents/Repositories/capi-multisig-app/node_modules/.pnpm/capi@0.1.0-beta.37/node_modules/capi/esm/rune/Rune.js:222:20)
      at async RunRehandle._evaluate (file:///home/ryan/Documents/Repositories/capi-multisig-app/node_modules/.pnpm/capi@0.1.0-beta.37/node_modules/capi/esm/rune/ValueRune.js:235:20)
      at async RunRehandle.evaluate (file:///home/ryan/Documents/Repositories/capi-multisig-app/node_modules/.pnpm/capi@0.1.0-beta.37/node_modules/capi/esm/rune/Rune.js:222:20)
      at async ValueRune.iter (file:///home/ryan/Documents/Repositories/capi-multisig-app/node_modules/.pnpm/capi@0.1.0-beta.37/node_modules/capi/esm/rune/Rune.js:80:31)
      at async ValueRune.run (file:///home/ryan/Documents/Repositories/capi-multisig-app/node_modules/.pnpm/capi@0.1.0-beta.37/node_modules/capi/esm/rune/Rune.js:68:26)
}
```

This should be resolved by just adding  `.sort()` to the end of `otherSignatories`

### PR DESCRIPTION
**Pull request by ryanleecode**
fixes #992

### CODE REVIEW

File: patterns/multisig/MultisigRune.ts [hunk 1]
```diff
@@ -155,3 +157,17 @@ export class MultisigRune<out C extends Chain, out U> extends PatternRune<Multis
 export class NoProposalError extends Error {
   override readonly name = "NoProposalError"
 }
+
+function compare(a: Uint8Array, b: Uint8Array): number {
```
Comment (tjjfvi) [inline patterns/multisig/MultisigRune.ts:161]: Pretty sure the same thing that exports `equals` has a `compare`

Comment (ryanleecode) [reply patterns/multisig/MultisigRune.ts:161]: this? https://deno.land/std@0.185.0/bytes/mod.ts

Comment (harrysolovay) [reply patterns/multisig/MultisigRune.ts:161]: Doesn't seem such a fn exists for `Uint8Array`s. Could we move this fn into a new util file? What shall we name it? `compareBytes`, `compareBuf`, ...

Comment (ryanleecode) [reply patterns/multisig/MultisigRune.ts:161]: Can just do `bytes` and throw all the missing byte related functions in there as they come up

Comment (harrysolovay) [reply patterns/multisig/MultisigRune.ts:161]: Good thinking. Would we want to `export * as bytes from "./bytes.ts"` in `util/mod.ts`?

Comment (ryanleecode) [reply patterns/multisig/MultisigRune.ts:161]: Yeah i think that would be good, since `compare` is so generic its good to namespace it.

File: patterns/multisig/MultisigRune.ts [hunk 2]
```diff
@@ -1,6 +1,7 @@
 import { MultiAddress } from "@capi/polkadot"
 import * as bytes from "../../deps/std/bytes.ts"
 import { $, Chain, ChainRune, PatternRune, Rune, RunicArgs, ValueRune } from "../../mod.ts"
+import * as util from "../../util/mod.ts"
```
Comment (harrysolovay) [inline patterns/multisig/MultisigRune.ts:4]: Can we `import { bytes }` instead?

Comment (ryanleecode) [reply patterns/multisig/MultisigRune.ts:4]: We are already importing bytes from std

Comment (ryanleecode) [reply patterns/multisig/MultisigRune.ts]: Im going to just merge it with std i think that is more preferrable

File: deps/std/bytes.ts [hunk 3]
```diff
@@ -1 +1,15 @@
 export * from "https://deno.land/std@0.185.0/bytes/mod.ts"
+
```
Comment (ryanleecode) [inline deps/std/bytes.ts:2]: alternatively we can still have a `bytes.ts` file under util and have that file re-export the std bytes library. might be cleaner than _polluting_ the std namespace?

**Review by harrysolovay — APPROVED** [review]
