### PR TITLE
fix: cors server errors

### LINKED ISSUE #793: cors errors when running examples in browser
```
Access to fetch at 'http://localhost:4646/frame/dev/polkadot/@v0.9.37/user_i' from origin 'null' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
VM25:2942          POST http://localhost:4646/frame/dev/polkadot/@v0.9.37/user_i net::ERR_FAILED
users2 @ VM25:2942
(anonymous) @ VM25:21410
VM20:2728 TypeError: Failed to fetch
    at users2 (<anonymous>:2942:28)
    at <anonymous>:21410:21
```

### PR DESCRIPTION
**Pull request by ryanleecode**
Resolves #793

### CODE REVIEW

File: providers/frame/common.ts [hunk 1]
```diff
@@ -58,17 +58,23 @@ export const createUsers ${
...
-  const { count } = body
-  const index = cache.count
-  const newCount = index + count
-  if (newCount < DEFAULT_TEST_USER_COUNT) cache.count = newCount
-  else throw new Error("Maximum test user count reached")
-  return new Response(JSON.stringify({ index }), {
-    status: 200,
-    headers: { "Content-Type": "application/json" },
-  })
+  switch (request.method) {
```
Comment (tjjfvi) [inline providers/frame/common.ts:61]: Why was this change made?

Comment (ryanleecode) [reply providers/frame/common.ts:61]: When it does cors it sends a OPTION request to this endpoint. that request doesnt have a body so it would just crash

Comment (tjjfvi) [reply providers/frame/common.ts:61]: In that case, can you handle OPTIONS requests in `handleCors`?

Comment (ryanleecode) [reply providers/frame/common.ts:61]: Wouldn't it still crash since this handler would trigger before `handleCors`?

Comment (ryanleecode) [reply providers/frame/common.ts:61]: I guess it would be caught by the handleError we would just ignore the response

Comment (tjjfvi) [reply providers/frame/common.ts:61]: > Wouldn't it still crash since this handler would trigger before `handleCors`?

I was suggesting that you check in `handleCors` if the method is `OPTIONS` before calling the inner handler

**Review by tjjfvi — APPROVED** [review]
